version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.7.4
      - image: anoikis/postgres
      - image: circleci/redis

    # working_directory: ~/postschema

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: where am I
          command: |
            pwd

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run db bootstraping
      # - run:
      #     name: db bootstrap
      #     command: |
      #       . venv/bin/activate
      #       python3 tests/mock/provision_db.py

      # # run tests
      # - run:
      #     name: run tests
      #     command: |
      #       . venv/bin/activate
      #       python3 

      # - store_artifacts:
      #     path: test-reports
      #     destination: test-reports